# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('author_email', models.EmailField(blank=True, max_length=240, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
