# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
    ]
