# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180617_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AddField(
            model_name='postcategory',
            name='brief',
            field=models.CharField(default='1', max_length=500),
            preserve_default=False,
        ),
    ]
