# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180617_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='photo2',
        ),
    ]
